<a href="https://colab.research.google.com/github/sunmarknatecom/colaboratory/blob/master/create_heatmap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### refernce: https://stackoverflow.com/questions/58322147/how-to-generate-cnn-heatmaps-using-built-in-keras-in-tf2-0-tf-keras

In [0]:
from tensorflow.keras.applications.vgg16 import preprocess_input
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.models import load_model

from tensorflow.keras import preprocessing
from tensorflow.keras import backend as K
from tensorflow.keras import models

import tensorflow as tf
import numpy as np

In [0]:
image_size = 224

#### [] Load pre-trained Keras model and the image to classify

In [0]:
model = tf.keras.applications.vgg16.VGG16()
image = np.random.random((image_size, image_size, 3))
image

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


array([[[4.50362359e-01, 5.76696259e-01, 4.70385729e-01],
        [4.84771944e-01, 7.44203233e-01, 2.51244972e-01],
        [4.31353114e-01, 6.08631698e-01, 4.06229310e-01],
        ...,
        [5.61766106e-01, 5.74032561e-01, 6.10594910e-01],
        [5.55889038e-01, 4.38008498e-02, 7.75020853e-01],
        [6.51884374e-01, 7.12927860e-01, 9.09527752e-01]],

       [[3.57668607e-01, 8.77291009e-01, 5.48217638e-01],
        [8.38151006e-01, 8.19322661e-01, 9.30846540e-01],
        [3.36308249e-01, 4.15647415e-01, 3.30619122e-01],
        ...,
        [1.66606025e-01, 3.84502898e-01, 9.85213761e-02],
        [8.14168558e-01, 8.77928985e-01, 4.59049508e-01],
        [5.26700522e-01, 7.99410256e-02, 1.58458920e-01]],

       [[1.93380119e-01, 8.80393329e-01, 7.75824690e-01],
        [5.21735587e-01, 9.07217031e-01, 5.27992768e-01],
        [1.78064661e-01, 4.12239062e-02, 9.84864150e-02],
        ...,
        [5.36878811e-01, 9.19834690e-01, 7.98322935e-01],
        [8.98167262e-01, 9.32

In [0]:
np.shape(image)

(224, 224, 3)

In [0]:
img_tensor = preprocessing.image.img_to_array(image)
img_tensor

array([[[4.5036235e-01, 5.7669628e-01, 4.7038573e-01],
        [4.8477194e-01, 7.4420321e-01, 2.5124496e-01],
        [4.3135312e-01, 6.0863167e-01, 4.0622932e-01],
        ...,
        [5.6176609e-01, 5.7403255e-01, 6.1059493e-01],
        [5.5588901e-01, 4.3800849e-02, 7.7502084e-01],
        [6.5188438e-01, 7.1292788e-01, 9.0952778e-01]],

       [[3.5766861e-01, 8.7729102e-01, 5.4821765e-01],
        [8.3815098e-01, 8.1932265e-01, 9.3084651e-01],
        [3.3630824e-01, 4.1564742e-01, 3.3061913e-01],
        ...,
        [1.6660602e-01, 3.8450289e-01, 9.8521374e-02],
        [8.1416857e-01, 8.7792897e-01, 4.5904949e-01],
        [5.2670050e-01, 7.9941027e-02, 1.5845892e-01]],

       [[1.9338012e-01, 8.8039333e-01, 7.7582467e-01],
        [5.2173561e-01, 9.0721703e-01, 5.2799278e-01],
        [1.7806466e-01, 4.1223906e-02, 9.8486416e-02],
        ...,
        [5.3687882e-01, 9.1983467e-01, 7.9832292e-01],
        [8.9816725e-01, 9.3226478e-04, 1.4982459e-01],
        [9.6790653e-01

In [0]:
np.shape(img_tensor)

(224, 224, 3)

In [0]:
img_tensor = np.expand_dims(img_tensor, axis=0)
np.shape(img_tensor)

(1, 224, 224, 3)

In [0]:
img_tensor

array([[[[4.5036235e-01, 5.7669628e-01, 4.7038573e-01],
         [4.8477194e-01, 7.4420321e-01, 2.5124496e-01],
         [4.3135312e-01, 6.0863167e-01, 4.0622932e-01],
         ...,
         [5.6176609e-01, 5.7403255e-01, 6.1059493e-01],
         [5.5588901e-01, 4.3800849e-02, 7.7502084e-01],
         [6.5188438e-01, 7.1292788e-01, 9.0952778e-01]],

        [[3.5766861e-01, 8.7729102e-01, 5.4821765e-01],
         [8.3815098e-01, 8.1932265e-01, 9.3084651e-01],
         [3.3630824e-01, 4.1564742e-01, 3.3061913e-01],
         ...,
         [1.6660602e-01, 3.8450289e-01, 9.8521374e-02],
         [8.1416857e-01, 8.7792897e-01, 4.5904949e-01],
         [5.2670050e-01, 7.9941027e-02, 1.5845892e-01]],

        [[1.9338012e-01, 8.8039333e-01, 7.7582467e-01],
         [5.2173561e-01, 9.0721703e-01, 5.2799278e-01],
         [1.7806466e-01, 4.1223906e-02, 9.8486416e-02],
         ...,
         [5.3687882e-01, 9.1983467e-01, 7.9832292e-01],
         [8.9816725e-01, 9.3226478e-04, 1.4982459e-01],
  

In [0]:
img_tensor = preprocess_input(img_tensor)
np.shape(img_tensor)

(1, 224, 224, 3)

In [0]:
img_tensor

array([[[[-103.46862 , -116.2023  , -123.22964 ],
         [-103.68776 , -116.0348  , -123.19523 ],
         [-103.532776, -116.170364, -123.24865 ],
         ...,
         [-103.32841 , -116.20496 , -123.11823 ],
         [-103.16398 , -116.7352  , -123.124115],
         [-103.02947 , -116.06607 , -123.028114]],

        [[-103.390785, -115.90171 , -123.322334],
         [-103.008156, -115.95968 , -122.84185 ],
         [-103.60838 , -116.36335 , -123.34369 ],
         ...,
         [-103.840485, -116.39449 , -123.5134  ],
         [-103.47995 , -115.90107 , -122.86583 ],
         [-103.78054 , -116.69906 , -123.1533  ]],

        [[-103.16318 , -115.898605, -123.48662 ],
         [-103.41101 , -115.87178 , -123.158264],
         [-103.840515, -116.73778 , -123.50194 ],
         ...,
         [-103.14068 , -115.85916 , -123.14312 ],
         [-103.78918 , -116.77807 , -122.78183 ],
         [-103.08374 , -116.28227 , -122.7121  ]],

        ...,

        [[-103.79623 , -115.8332  , -1

In [0]:
np.shape(img_tensor)

(1, 224, 224, 3)

In [0]:
conv_layer = model.get_layer("block5_conv3")
heatmap_model = models.Model([model.inputs], [conv_layer.output, model.output])

In [0]:
heatmap_model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0     

In [0]:
with tf.GradientTape() as gtape:
    conv_output, predictions = heatmap_model(img_tensor)
    loss = predictions[:, K.argmax(predictions[0])]
    grads = gtape.gradient(loss, conv_output)
    pooled_grads = K.mean(grads, axis=(0, 1, 2))

### [] Get gradient of the winner class w.r.t. the output of the (last) conv. layer

### np.

In [0]:
heatmap = tf.reduce_mean(tf.multiply(pooled_grads, conv_output), axis=-1)
heatmap = K.maximum(heatmap, 0)
max_heat = K.max(heatmap)
if max_heat == 0:
    max_heat = 1e-10
heatmap /= max_heat

print(heatmap.shape)

(1, 14, 14)


In [0]:
heatmap

<tf.Tensor 'truediv:0' shape=(1, 14, 14) dtype=float32>